Objetivo 7 [IV-21-22]
alexespana/Proyecto-IV pull request #47
Opened 2021-12-13 20:50 UTC by alexespana

2021-12-14 15:01 UTC, alexespana commented
Listo para revisión.

2021-12-17 06:37 UTC, JJ requested changes
Aparte de que el milestone se llama exactamente igual que el que tú ya sabes, tiene exactamente el mismo problema.

2021-12-17 07:45 UTC, alexespana commented
> Aparte de que el milestone se llama exactamente igual que el que tú ya sabes, tiene exactamente el mismo problema.

Lo he llamado así porque el objetivo 7 se llama servicios esenciales en la nube, sin más. ¿Cuál sería el problema que tiene?

2021-12-17 09:16 UTC, alexespana commented
> Aparte de que el milestone se llama exactamente igual que el que tú ya sabes, tiene exactamente el mismo problema.

Vale, creo que mejoré el milestone.

2021-12-17 09:16 UTC, alexespana commented
Listo para revisión @JJ

2021-12-17 10:36 UTC, JJ commented
A ver, ese "tets" de Circle...

2021-12-17 10:51 UTC, JJ commented on README.md
> +y la API podría cambiar, además de que no cumple con el requisito de que sea habitualmente mantenida (último commit hace más de un año).
Si es versión 0, es probable.

2021-12-17 10:51 UTC, JJ commented on README.md
> +configurar, Por esta razón se ha decidido usar **etcd3** directamente, como se nos recomendó en clase de teoría. Es importante tener en cuenta que en esta fase estamos realizando la configuración del
mayúsculas después de coma

2021-12-17 10:51 UTC, JJ commented on bar_power/config.py
> +            load_dotenv('bar_power/config.env')
Deberías usar un fichero estándar como `env` o `config.env`. Ten en cuenta que no va a estar en el repo, así que quien lo use puede volverse un poco loco.

2021-12-17 10:51 UTC, JJ commented on bar_power/config.py
> +                self.log_directory = '/tmp/barpower/log/'   # Lugar con permisos de escritura
Supongo que este directorio lo construirá si no existe.

2021-12-17 10:51 UTC, JJ commented on bar_power/handler.py
> +            raise exception
Lo hemos explicado hoy en clase dividida (pregúntale a @amerigal @mapachana @modejota). No puedes levantar las excepciones desde el manejador de forma arbitraria.

2021-12-17 10:51 UTC, JJ commented on bar_power/logger.py
> +configutation = Config()
typo. También, variable de módulo, no es una buena costumbre. Y una vez más, es la misma mala costumbre que tú ya sabes quién.

2021-12-17 11:06 UTC, modejota commented on bar_power/handler.py
> +            raise exception
Por lo que he entendido, el manejador podrá levantar excepciones que tenga sentido que la API maneje, como un ID que no existe, pero no errores porque sí. El error llegaría al cliente y sería una movida; sobre todo si hay un servicio técnico que debe asistirle, y que por lo visto son super caros :(

2021-12-17 11:16 UTC, JJ reviewed
Corrige los errores que te comento, por favor.

2021-12-17 11:16 UTC, JJ commented on bar_power/handler.py
> +            raise exception
Soporte técnico, no servicio técnico... Aunque los servicios técnicos sí suelen ser super caros...

2021-12-17 11:16 UTC, JJ commented on bar_power/logger.py
> +    os.makedirs(LOG_DIRECTORY, exist_ok=True)
No estás capturando ninguna excepción aquí. Y una vez más, código de módulo, mala costumbre, se ejecutará al cargar el módulo.

2021-12-17 11:16 UTC, JJ commented on bar_power/logger.py
> +logging.basicConfig(filename=LOG_DIRECTORY + LOG_FILE, level=logging.DEBUG, format='%(asctime)s <=> %(levelname)s <=> %(pathname)s <=> %(message)s' )
Tampoco es una buena costumbre. Deberías usar, y exportar, un objeto, porque luego en el API lo vas a necesitar.

2021-12-17 13:05 UTC, alexespana commented on README.md
> +configurar, Por esta razón se ha decidido usar **etcd3** directamente, como se nos recomendó en clase de teoría. Es importante tener en cuenta que en esta fase estamos realizando la configuración del
Arreglado

2021-12-17 13:05 UTC, alexespana commented on bar_power/config.py
> +            load_dotenv('bar_power/config.env')
Cambiado

2021-12-17 13:05 UTC, alexespana commented on bar_power/config.py
> +                self.log_directory = '/tmp/barpower/log/'   # Lugar con permisos de escritura
Sí

2021-12-17 13:05 UTC, alexespana commented on bar_power/logger.py
> +    os.makedirs(LOG_DIRECTORY, exist_ok=True)
Arreglado

2021-12-17 13:11 UTC, alexespana commented
Listo para revisión @JJ

2021-12-17 19:16 UTC, JJ requested changes
Algo mejor, pero sigues sin solucionar los problemas señalados.

2021-12-17 19:16 UTC, JJ commented on bar_power/logger.py
> +logging.basicConfig(filename=LOG_DIRECTORY + LOG_FILE, level=logging.DEBUG, format='%(asctime)s <=> %(levelname)s <=> %(pathname)s <=> %(message)s' )
Ping

2021-12-17 19:16 UTC, JJ commented on bar_power/handler.py
> +            raise exception
Ping

2021-12-17 19:27 UTC, alexespana commented on bar_power/handler.py
> +            raise exception
Veo por dónde van los tiros, mañana lo miro con más detenimiento, hoy no voy a poder.

2021-12-17 19:28 UTC, alexespana commented on bar_power/logger.py
> +logging.basicConfig(filename=LOG_DIRECTORY + LOG_FILE, level=logging.DEBUG, format='%(asctime)s <=> %(levelname)s <=> %(pathname)s <=> %(message)s' )
Entiendo, intentaré arrreglarlo cuanto antes

2021-12-18 01:56 UTC, alexespana commented
Bueno, creo que ya estaría todo arreglado :sleepy: .

2021-12-18 01:56 UTC, alexespana commented
Listo para revisión @JJ .

2021-12-21 12:22 UTC, JJ requested changes
Además de lo dicho, el milestone tiene una lista de tareas más que una descripción real del producto, que incluiría también la captura de eventos (#45) y demás.

2021-12-21 12:22 UTC, JJ commented on bar_power/logger.py
> +        logging.basicConfig(filename=self.log_directory + self.log_file, level=self.level, format=self.format)
Sigues sin usar un objeto de log. Haces llamadas a la clase, en vez de instanciar un objeto como indica en el manual

2021-12-21 16:11 UTC, alexespana commented on bar_power/logger.py
> +        logging.basicConfig(filename=self.log_directory + self.log_file, level=self.level, format=self.format)
¿Se refiere a instanciar  un objeto logger con logging.getLogger() y usar éste internamente dentro de la clase Logger?

2021-12-22 01:25 UTC, alexespana commented
Listo para revisión @JJ .

2021-12-22 07:53 UTC, JJ approved these changes
Bastante completo, y muy completas también las revisiones que haces :clap:

2021-12-22 17:56 UTC, merged